@AbapCatalog.viewEnhancementCategory: [#NONE]
@AccessControl.authorizationCheck: #NOT_REQUIRED
@EndUserText.label: 'KNA1 - CDS View'
@Metadata.ignorePropagatedAnnotations: true
@ObjectModel.usageType:{
    serviceQuality: #X,
    sizeCategory: #S,
    dataClass: #MIXED
}
@OData.publish: true
define view entity ZKNA1_CDS as select from I_Customer
{
    key Customer,
    CustomerName,
    CustomerFullName,
    CreatedByUser,
    CreationDate,
    AddressID,
    CustomerClassification,
    VATRegistration,
    CustomerAccountGroup,
    AuthorizationGroup,
    DeliveryIsBlocked,
    PostingIsBlocked,
    BillingIsBlockedForCustomer,
    OrderIsBlockedForCustomer,
    InternationalLocationNumber1,
    IsOneTimeAccount,
    TaxJurisdiction,
    Industry,
    TaxNumberType,
    TaxNumber1,
    TaxNumber2,
    TaxNumber3,
    TaxNumber4,
    TaxNumber5,
    TaxNumber6,
    CustomerCorporateGroup,
    Supplier,
    NielsenRegion,
    IndustryCode1,
    IndustryCode2,
    IndustryCode3,
    IndustryCode4,
    IndustryCode5,
    Country,
    OrganizationBPName1,
    OrganizationBPName2,
    CityName,
    PostalCode,
    StreetName,
    SortField,
    FaxNumber,
    BR_SUFRAMACode,
    Region,
    TelephoneNumber1,
    TelephoneNumber2,
    AlternativePayerAccount,
    DataMediumExchangeIndicator,
    VATLiability,
    IsBusinessPurposeCompleted,
    ResponsibleType,
    FiscalAddress,
    NFPartnerIsNaturalPerson,
    DeletionIndicator,
    Language,
    TradingPartner,
    DeliveryDateTypeRule,
    ExpressTrainStationName,
    TrainStationName,
    InternationalLocationNumber2,
    InternationalLocationNumber3,
    CityCode,
    County,
    CustomerHasUnloadingPoint,
    CustomerWorkingTimeCalendar,
    IsCompetitor,
    TaxInvoiceRepresentativeName,
    BusinessType,
    IndustryType,
    TW_CollvBillingIsSupported,
    AlternativePayeeIsAllowed,
    FreeDefinedAttribute01,
    FreeDefinedAttribute02,
    FreeDefinedAttribute03,
    FreeDefinedAttribute04,
    FreeDefinedAttribute05,
    FreeDefinedAttribute06,
    FreeDefinedAttribute07,
    FreeDefinedAttribute08,
    FreeDefinedAttribute09,
    FreeDefinedAttribute10,
    PaymentReason,
    IsSalesProspect,
    PaymentIsBlockedForCustomer,
    /* Associations */
    _AddressDefaultRepresentation,
    _ContactPerson,
    _CorrespondingSupplier,
    _CreatedByUser,
    _CustomerAccountGroupText,
    _CustomerAddr,
    _CustomerAddrSalesAreaTax,
    _CustomerClassification,
    _CustomerClassificationText,
    _CustomerCompany,
    _CustomerHierarchyNode,
    _CustomerSalesArea,
    _CustomerSalesAreaTax,
    _CustomerToBusinessPartner,
    _GlobalCompany,
    _StandardAddress
}
